# Generated by Django 3.2 on 2021-05-14 02:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Moddle', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='ending_time',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='starting_time',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='lecturer',
            name='dob',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='dob',
            field=models.DateField(null=True),
        ),
    ]
